[package]
name = "bevy-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17" }
bevy_example_app = { path = "crates/bevy_example_app" }

[[example]]
name = "hello_world"
path = "examples/hello_world/main.rs"

[[example]]
name = "2d_shapes"
path = "examples/2d_shapes/main.rs"

[[example]]
name = "player_move"
path = "examples/player_move/main.rs"
